### ISSUE TITLE
Grammer in README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/coding-youtubers#13]
It's currently Teaches Web Development, would it be better if it is Makes Tutorials on Web Development?

What do you think on this @vikasganiga05 @AnimeshKumar923?

**Comment by AnimeshKumar923** [comment]
Who teaches web development?

Elaborate a little more...

**Comment by KendallDoesCoding** [comment]
> Who teaches web development?
> 
> Elaborate a little more...

ex: 
![image](https://user-images.githubusercontent.com/84712013/182686920-804a320e-9843-447e-ad7a-19b93795baca.png)

**Comment by AnimeshKumar923** [comment]
I think it can be 'Makes content around web development'.

Thoughts? @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> I think it can be 'Makes content around web development'.
> 
> Thoughts? @KendallDoesCoding

Good idea!

**Comment by AnimeshKumar923** [comment]
'Makes content about web development' 

This should be better.

**Comment by KendallDoesCoding** [comment]
> 'Makes content about web development'
> 
> This should be better.

wdym?

**Comment by AnimeshKumar923** [comment]
I'm saying that writing it like this would be better:

"Makes content about web development"

**Comment by KendallDoesCoding** [comment]
@AnimeshKumar923 Please join organization at the earliest, can't make you review PR's, etc till you join.

**Comment by KendallDoesCoding** [comment]
> I'm saying that writing it like this would be better:
> 
> "Makes content about web development"

Yup, I got that from this:

> I think it can be 'Makes content around web development'.

Thoughts? @KendallDoesCoding

**Comment by AnimeshKumar923** [comment]
> @AnimeshKumar923 Please join organization at the earliest, can't make you review PR's, etc till you join.

Will join after 12 hours, going to sleep in 20 mins 😅

**Comment by KendallDoesCoding** [comment]
> > @AnimeshKumar923 Please join organization at the earliest, can't make you review PR's, etc till you join.
> 
> Will join after 12 hours, going to sleep in 20 mins 😅

no worries, i didn't realize the time, dang its late lol
