### ISSUE TITLE
Rank channels in subscriber order.

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/coding-youtubers#20]
After completing #4 , we can rank channels in subscriber order, within their alphabet using the help of #21.

What do you think about this @vikasganiga05?

**Comment by AnimeshKumar923** [comment]
@KendallDoesCoding I don't think this is a good criteria to rank according to subscribers.

It should be topic-wise not subscriber-wise because you need to learn a language or technology and not count the subscribers.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding I don't think this is a good criteria to rank according to subscribers.
> 
> It should be topic-wise not subscriber-wise because you need to learn a language or technology and not count the subscribers.

Yeah true. Closing this issue, can you create a issue similar to this, to sort it topic-wise or should I do that?

**Comment by AnimeshKumar923** [comment]
> > @KendallDoesCoding I don't think this is a good criteria to rank according to subscribers.
> > 
> > It should be topic-wise not subscriber-wise because you need to learn a language or technology and not count the subscribers.
> 
> Yeah true. Closing this issue, can you create a issue similar to this, to sort it topic-wise or should I do that?

Already there, I guess #7

**Comment by KendallDoesCoding** [comment]
> > > @KendallDoesCoding I don't think this is a good criteria to rank according to subscribers.
> > > It should be topic-wise not subscriber-wise because you need to learn a language or technology and not count the subscribers.
> > 
> > 
> > Yeah true. Closing this issue, can you create a issue similar to this, to sort it topic-wise or should I do that?
> 
> Already there, I guess #7

That's not exactly to rank channels in a certain order, but we'll do this after we're done with #7 anyway!

**Comment by AnimeshKumar923** [comment]
> > > > @KendallDoesCoding I don't think this is a good criteria to rank according to subscribers.
> > > > It should be topic-wise not subscriber-wise because you need to learn a language or technology and not count the subscribers.
> > > 
> > > 
> > > Yeah true. Closing this issue, can you create a issue similar to this, to sort it topic-wise or should I do that?
> > 
> > 
> > Already there, I guess #7
> 
> That's not exactly to rank channels in a certain order, but we'll do this after we're done with #7 anyway!

Ok, will look into that after a while.

**Comment by KendallDoesCoding** [comment]
Ok cool, thanks.
