### ISSUE TITLE
Add an Open Source license.

### ISSUE THREAD

**Issue by fluentmoheshwar** [collab-community/coding-youtubers#24]
Add an Open Source license to allow use, modify, or share the software.
According to https://choosealicense.com/no-permission/
If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
I think adding a license is necessary.
I recommend adding MIT License..

**Comment by KendallDoesCoding** [comment]
Yeah, I know but I forgot to add it.

I think we can add "The Unlicense" (https://github.com/collab-community/become-a-member/blob/main/LICENSE) or MIT License for this project.

Please give me your inputs @collab-community/coding-youtubers

**Comment by fluentmoheshwar** [comment]
My choice is MIT.

**Comment by Adarsh-jaiss** [comment]
-- I will also suggest to go with the MIT licence

**Comment by KendallDoesCoding** [comment]
Ok, let's proceed with MIT in that case.
