### ISSUE TITLE
Header of Table not Bold on Website.

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/coding-youtubers#33]
The header of table, "Name", "Description" & "Language" are not bold on the website for some reason.

I require someone to fix this issue at the earliest.

@Agrim-Sharma174 please have a look.

**Comment by AnimeshKumar923** [comment]
I would like to add to this:

The table boundaries on website should be a bit darker.

**Comment by KendallDoesCoding** [comment]
> 

Thanks for your interest! Assigning you.

**Comment by KendallDoesCoding** [comment]
@nettle790 , #36 messed up the website.

**Comment by KendallDoesCoding** [comment]
LOL, i just said trying to fix #33, didn't think it will close the issue, but it did fix, so saved my time ig.
