### ISSUE TITLE
Organize the channels automatically by language whenever a new channel is added

### ISSUE THREAD

**Issue by Agrim-Sharma174** [collab-community/coding-youtubers#40]
Is there a way, we can automatically order the channels by ENGLISH- HINDI- BENGALI? Whenever any new one is added?

**Comment by Agrim-Sharma174** [comment]
@Adarsh-jaiss @vikasganiga05 If possible, then this will help to follow the content easily, maybe an API if there's any

**Comment by KendallDoesCoding** [comment]
> @Adarsh-jaiss @vikasganiga05 If possible, then this will help to follow the content easily, maybe an API if there's any

even a Workflow or gh-action will work.

**Comment by adityajoshi-08** [comment]
Vikas most we shall try adding content in English and Hindi. It is more generalised and there aren't many good resources available in regional languages.
