### ISSUE TITLE
Transfer CONTRIBUTING.md and update the hyperlink

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/coding-youtubers#42]
- Transfer CONTRIBUING.md to the GitHub directory.
- Update hyperlink in README.md with updated path.

Can you work on this @AlphaDojo?

**Comment by AlphaDojo** [comment]
Yes I can do this. Should be no problem.

**Comment by AlphaDojo** [comment]
I sent a pull request for this issue.
