### ISSUE TITLE
Adding new youtube channel

### ISSUE THREAD

**Issue by Preet-Sojitra** [collab-community/coding-youtubers#44]
I want to contribute to this project by adding more youtube channels.
Where should I append new channels? Should I append it to top to at bottom or adding anywhere in between will be fine?

**Comment by KendallDoesCoding** [comment]
> I want to contribute to this project by adding more youtube channels. Where should I append new channels? Should I append it to top to at bottom or adding anywhere in between will be fine?

Hi, if the channel is English, put it at the end of "English" after "[Programming Hero](https://www.youtube.com/ProgrammingHero)". If the channel is Hindi, in the end of Hindi after [CodeHelp - by Babbar](https://www.youtube.com/CodeHelpbyBabbar) and so on, hope that helped!
