### ISSUE TITLE
[FEAT] Categorize the YouTube Channels

### ISSUE THREAD

**Issue by vikasganiga05** [collab-community/coding-youtubers#7]
It will be good to categorize the YouTube channels by video language, topics, everyday uploads, etc.

> For Example :point_down: 

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Language</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/Freecodecamp">freeCodeCamp.org</a></strong>
      </td>
      <td>All types of coding video.</td>
      <td>English</td>
    </tr>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/KunalKushwaha">Kunal Kushwaha</a></strong>
      </td>
      <td>Empowering communities via open-source and education.</td>
      <td>English, Hindi</td>
    </tr>
  </tbody>
</table>

> Code for the above table :point_down: 

```html
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Language</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/Freecodecamp">freeCodeCamp.org</a></strong>
      </td>
      <td>All types of coding video.</td>
      <td>English</td>
    </tr>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/KunalKushwaha">Kunal Kushwaha</a></strong>
      </td>
      <td>Empowering communities via open-source and education.</td>
      <td>English, Hindi</td>
    </tr>
  </tbody>
</table>
```

**Comment by KendallDoesCoding** [comment]
This is a amazing idea Vikas! Can you create a PR to do this for the current channels listed, they are all English

**Comment by KendallDoesCoding** [comment]
The list is getting very long, We should do this at the earliest.

@collab-community/coding-youtubers - please let me know who can work on this.

**Comment by KendallDoesCoding** [comment]
Assigned as per conversation.

**Comment by KendallDoesCoding** [comment]
We can also add a new row, called subscribers with the number of subscribers as discussed in #21 if there is a API out there.

**Comment by vikasganiga05** [comment]
Hi, Kendall is Agrim working on this?

**Comment by vikasganiga05** [comment]
If we update the list to table format like below :point_down: , then we need to remove those language categories(English & Hindi) right?

![image](https://user-images.githubusercontent.com/74750414/182736538-67e96c6d-6a88-4768-9535-5b76cb3b4ed4.png)

**Comment by KendallDoesCoding** [comment]
Yes!

**Comment by KendallDoesCoding** [comment]
Yup, I discussed that with Agrim, I added the language categories only for
now.

**Comment by vikasganiga05** [comment]
> 

Oh! Okay.

**Comment by vikasganiga05** [comment]
I updated the issue description. Added the code snippet for the table.

**Comment by fluentmoheshwar** [comment]
How about this?
<h1>English,/h1>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/Freecodecamp">freeCodeCamp.org</a></strong>
      </td>
      <td>All types of coding video.</td>
<h1>Hindi/h1>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>
      <td>
        <strong><a href="https://youtube.com/c/KunalKushwaha">Kunal Kushwaha</a></strong>
      </td>
      <td>Empowering communities via open-source and education.</td>
    </tr>
  </tbody>
</table>

**Comment by fluentmoheshwar** [comment]
It looks confusing to me. Languages should be separated.

**Comment by KendallDoesCoding** [comment]
> I updated the issue description with a code snippet for the table.

wdym?

**Comment by Abhinavkar** [comment]
> I updated the issue description with a code snippet for the table.

can i work on this issue

**Comment by KendallDoesCoding** [comment]
> > I updated the issue description with a code snippet for the table.
> 
> can i work on this issue

Hi, actually @Agrim-Sharma174 has already finished with this and waiting for his PR to be reviewed by @vikasganiga05 , #28
