### ISSUE TITLE
Improve Grammer in README

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/coding-youtubers#9]
I think there are a couple of grammer errors, please fix grammer issues in README.md and create a PR.

You can use tools like Grammerly, [Writer.com](https://writer.com/grammar-checker/)

**Comment by AnimeshKumar923** [comment]
I would like to work on improving grammar of the readme file.

**Comment by KendallDoesCoding** [comment]
> I would like to work on improving grammar of the readme file.

Sure! Assigned you, but seems that @LalitDhane already made a PR, sorry!

**Comment by KendallDoesCoding** [comment]
> > I would like to work on improving grammar of the readme file.
> 
> Sure! Assigned you, but seems that @LalitDhane already made a PR, sorry!

Merging both your PR's. @AnimeshKumar923 please resolve merge conflicts, @LalitDhane I merged yours.

**Comment by AnimeshKumar923** [comment]
> > > I would like to work on improving grammar of the readme file.
> > 
> > 
> > Sure! Assigned you, but seems that @LalitDhane already made a PR, sorry!
> 
> Merging both your PR's. @AnimeshKumar923 please resolve merge conflicts, @LalitDhane I merged yours.

Hey Kendall, I think the previous closed PR by @LalitDhane is conflicting with mine. What should we do about that?
